# Generated by Django 3.1.7 on 2021-04-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sur_name', models.CharField(max_length=50, verbose_name='Sur Name')),
                ('given_name', models.CharField(max_length=50, verbose_name='Given Name')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('father_name', models.CharField(max_length=50, verbose_name='Father Name')),
                ('mother_name', models.CharField(max_length=50, verbose_name='Mother Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('passport_no', models.IntegerField(blank=True, null=True, verbose_name='Passport Number')),
                ('mobile_number', models.CharField(max_length=50, verbose_name='Mobile Number')),
                ('date_of_birth', models.CharField(max_length=50, verbose_name='Date Of Birth')),
                ('nid_no', models.IntegerField(blank=True, null=True, verbose_name='Nid No')),
                ('religion', models.CharField(max_length=50, verbose_name='Religion')),
                ('marital_status', models.CharField(max_length=50, verbose_name='Marital Status')),
                ('spouse_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Spouse Name')),
                ('spouse_mobile_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Spouse Mobile Name')),
                ('interested_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Interested Country Name')),
                ('interested_institute', models.CharField(blank=True, max_length=50, null=True, verbose_name='Interested Instituted Name')),
                ('interested_program', models.CharField(max_length=50, verbose_name='Intersted Program ')),
                ('present_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Present Address')),
                ('permanent_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parmanent Address')),
                ('father_occupation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Father Ocopation')),
                ('father_designation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Father Desigantion')),
                ('father_mobile_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Father Mobile Number')),
                ('organization_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Organiazation Name')),
                ('organization_address', models.CharField(blank=True, max_length=50, null=True, verbose_name=' Organization Address')),
                ('reference_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference Name')),
                ('reference_mobile_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference Address')),
                ('referecnce_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='SSC Digree')),
                ('ssc_degree', models.CharField(blank=True, max_length=50, null=True, verbose_name='SSC Digree')),
                ('ssc_institute', models.CharField(blank=True, max_length=50, null=True, verbose_name='SSC Instute')),
                ('ssc_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('ssc_result', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('ssc_year', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('hsc_degree', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('hsc_institute', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('hsc_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('hsc_result', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('hsc_year', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sur Name')),
                ('bacholor_degree', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('bacholor_institute', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('bacholor_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('bacholor_result', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('bacholor_year', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('masters_degree', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('masters_institute', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('masters_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('masters_result', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('masters_year', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('language_skills', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('language_skills_score', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('language_skills_score_test_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('information_media', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('phone_contact_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('counselor_Name', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('visa_processed_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('digital_sign', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('photo_and_signeture', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('nid_and_passport', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('master_certificate_and_transcript', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('bachelor_certificate_and_transcript', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('hsc_certificate_and_transcript', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('ssc_certificate_and_transcript', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
            ],
        ),
    ]
