# Generated by Django 3.1.7 on 2021-04-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='bachelor_certificate_and_transcript',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='bachelor_certificate_and_transcript'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='bacholor_degree',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='bacholor_degree'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='bacholor_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='bacholor_group'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='bacholor_institute',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='bacholor_institute'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='bacholor_result',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='bacholor_result'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='bacholor_year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='bacholor_year'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='counselor_Name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='counselor_Name'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='digital_sign',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='digital_sign'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='hsc_certificate_and_transcript',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='hsc_certificate_and_transcript'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='hsc_degree',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='hsc_degree'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='hsc_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='hsc_group'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='hsc_institute',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='hsc_institute'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='hsc_result',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='hsc_result'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='hsc_year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='hsc_year'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='information_media',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='information_media'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='language_skills',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='language_skills'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='language_skills_score',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='language_skills_score'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='language_skills_score_test_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='language_skills_score_test_date'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='master_certificate_and_transcript',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='master_certificate_and_transcript'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='masters_degree',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='masters_degree'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='masters_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='masters_group'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='masters_institute',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='masters_institute'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='masters_result',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='masters_result'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='masters_year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='masters_year'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mother Name'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='nid_and_passport',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nid_and_passport '),
        ),
        migrations.AlterField(
            model_name='admission',
            name='phone_contact_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone_contact_by'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='photo_and_signeture',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='photo_and_signeture'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='ssc_certificate_and_transcript',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ssc_certificate_and_transcript'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='ssc_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ssc_group'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='ssc_result',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ssc_result'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='ssc_year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ssc_year'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='visa_processed_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='visa_processed_by'),
        ),
    ]
