# Generated by Django 3.1.7 on 2021-04-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20210402_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Gender'),
        ),
    ]
