# Generated by Django 3.1.6 on 2021-03-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_logo', models.ImageField(upload_to='pics')),
                ('university_name', models.CharField(max_length=255)),
                ('university_rank', models.CharField(max_length=50)),
                ('university_country', models.CharField(max_length=100)),
            ],
        ),
    ]
