# Generated by Django 3.1.6 on 2021-03-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Top University', 'verbose_name_plural': 'Top Universitys'},
        ),
        migrations.AddField(
            model_name='university',
            name='established_year',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='international_students',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='total_students',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='university_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='university_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_logo',
            field=models.ImageField(upload_to='pics', verbose_name='University Logo'),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_rank',
            field=models.IntegerField(default='0', max_length=20, verbose_name='Rank'),
        ),
    ]
