# Generated by Django 3.1.6 on 2021-03-21 11:18

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20210321_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='university_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
