# Generated by Django 3.1.6 on 2021-03-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydetails',
            options={'verbose_name': 'Company Detail', 'verbose_name_plural': 'Company Details'},
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='company_description',
            field=models.TextField(max_length=155, verbose_name='Company Description For Meta Details (Max Length 155)'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='company_keywords',
            field=models.TextField(default='abc, xyz, alpha,', max_length=160, verbose_name='Company keywords For Meta Details (Max Length 160)'),
        ),
    ]
