# Generated by Django 3.1.6 on 2021-03-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University_rank', models.IntegerField(default='0', verbose_name='Rank')),
                ('slider_title', models.CharField(max_length=255, verbose_name='Slider Title')),
                ('slider_image', models.ImageField(upload_to='slider_image', verbose_name='Slider Image')),
            ],
            options={
                'verbose_name': 'Home Page Slider',
                'verbose_name_plural': 'Home Page Sliders',
            },
        ),
    ]
