# Generated by Django 3.1.6 on 2021-03-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageslider',
            name='University_rank',
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='slider_sl',
            field=models.IntegerField(default='0', verbose_name='Slider Serial No'),
        ),
    ]
