# Generated by Django 3.1.6 on 2021-03-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_auto_20210324_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslider',
            name='slider_image',
            field=models.ImageField(upload_to='pics', verbose_name='Slider Image'),
        ),
    ]
