# Generated by Django 3.1.6 on 2021-03-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_auto_20210324_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageslider',
            name='slider_sl',
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='slider_image',
            field=models.ImageField(upload_to='slider_image', verbose_name='Slider Image'),
        ),
    ]
