# Generated by Django 3.1.6 on 2021-03-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_auto_20210324_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentClientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Client Name')),
                ('client_logo', models.ImageField(upload_to='client_logo', verbose_name='Client Business Logo')),
                ('client_profile_show_home_page', models.BooleanField(default=False, verbose_name='Show on Homepage')),
            ],
        ),
    ]
