# Generated by Django 3.1.6 on 2021-03-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0005_employmentclientlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageLeftSide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('External_video_Url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Upload Video Via Url (Youtube/Others)')),
                ('rightsidebaner1', models.ImageField(blank=True, null=True, upload_to='Banner', verbose_name='Right Side Baner 1')),
                ('rightsidebaner2', models.ImageField(blank=True, null=True, upload_to='Banner', verbose_name='Right Side Baner 2')),
                ('quotes', models.CharField(blank=True, max_length=150, null=True, verbose_name='quotes')),
                ('quotes_writter', models.CharField(blank=True, max_length=50, null=True, verbose_name='quotes_writter')),
            ],
        ),
        migrations.AlterModelOptions(
            name='employmentclientlist',
            options={'verbose_name': 'Employment Client', 'verbose_name_plural': 'Employment Clients'},
        ),
        migrations.AlterField(
            model_name='employmentclientlist',
            name='client_profile_show_home_page',
            field=models.BooleanField(default=False, verbose_name='Show on Home Page'),
        ),
    ]
