# Generated by Django 3.1.6 on 2021-03-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0006_auto_20210325_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageleftside',
            options={'verbose_name': 'Left Side Media', 'verbose_name_plural': 'Left Side Medias'},
        ),
    ]
