# Generated by Django 3.1.6 on 2021-03-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0009_auto_20210327_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(blank=True, max_length=150, null=True, verbose_name='Quote')),
                ('quote_writter', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quote Writter')),
                ('show_multipul_pages', models.BooleanField(default=False, verbose_name='Show Multipul Pages')),
                ('home_page', models.BooleanField(default=False, verbose_name='Home Page')),
                ('about_page', models.BooleanField(default=False, verbose_name='About Page')),
                ('team_page', models.BooleanField(default=False, verbose_name='Team Page')),
            ],
        ),
    ]
