# Generated by Django 3.1.6 on 2021-03-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0010_blockquote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockquote',
            name='quote',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Quote'),
        ),
    ]
