# Generated by Django 3.1.6 on 2021-03-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0011_auto_20210327_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('designation', models.CharField(blank=True, max_length=150, null=True, verbose_name='Designation')),
                ('department', models.CharField(blank=True, max_length=150, null=True, verbose_name='Department')),
                ('short_description', models.CharField(blank=True, max_length=150, null=True, verbose_name='short_description')),
            ],
        ),
    ]
