# Generated by Django 3.1.6 on 2021-03-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0012_manageteams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockquote',
            options={'verbose_name': 'Block Quote', 'verbose_name_plural': 'Block Quotes'},
        ),
        migrations.AlterModelOptions(
            name='manageteams',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AlterField(
            model_name='manageteams',
            name='short_description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='short_description'),
        ),
    ]
