# Generated by Django 3.1.7 on 2021-04-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0013_auto_20210327_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageteams',
            name='short_description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Short Description'),
        ),
    ]
